name: CI PR

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies (backend + test) + Preflight
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip

          # Backend deps
          if [ -f backend/requirements.txt ]; then
            pip install -r backend/requirements.txt
          fi

          # Test deps
          if [ -f backend/requirements-test.txt ]; then
            pip install -r backend/requirements-test.txt
          fi

          # Diagnóstico rápido
          pip freeze | grep -Ei 'python-docx|fpdf2|pypdf2' || true

          # Preflight: asegura módulos clave antes de lanzar pytest
          python - <<'PY'
          import pkgutil, sys
          required = ["docx", "fpdf", "PyPDF2"]
          status = {m: (pkgutil.find_loader(m) is not None) for m in required}
          print("Preflight deps ->", status)
          missing = [m for m, ok in status.items() if not ok]
          if missing:
              sys.stderr.write(f"Missing: {missing}\n")
              sys.exit(1)
          PY

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/backend/src
        run: pytest -q
