name: CI PR

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          if [ -f backend/requirements-test.txt ]; then pip install -r backend/requirements-test.txt; fi
          pip install python-docx fpdf2
          python -c "import pkgutil,sys; ok1=pkgutil.find_loader('docx') is not None; ok2=pkgutil.find_loader('fpdf') is not None; print(f'Has docx?: {ok1} | Has fpdf?: {ok2}'); sys.exit(0 if (ok1 and ok2) else 1)"

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/backend/src
        run: pytest -q
