name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          # Instala los requirements del backend (los que usa tu app y tests)
          pip install -r backend/requirements.txt
          if [ -f backend/requirements-test.txt ]; then
            pip install -r backend/requirements-test.txt
          fi
          # Salvavidas para este PR: garantiza estos paquetes
          pip install python-docx fpdf2
          # Verificación explícita
          python -c "import pkgutil,sys; ok1=pkgutil.find_loader('docx') is not None; ok2=pkgutil.find_loader('fpdf') is not None; print(f'Has docx?: {ok1} | Has fpdf?: {ok2}'); sys.exit(0 if (ok1 and ok2) else 1)"

      - name: Debug packages (optional)
        run: |
          pip freeze | grep -Ei 'docx|fpdf' || true
          python - <<'PY'
          import sys, pkgutil
          print('Python:', sys.version)
          print('docx present:', bool(pkgutil.find_loader('docx')))
          print('fpdf present:', bool(pkgutil.find_loader('fpdf')))
          try:
              import fpdf
              import os
              print('fpdf module file:', getattr(fpdf, '__file__', 'n/a'))
          except Exception as e:
              print('fpdf import error:', e)
          PY

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/backend/src
        run: pytest -q
