version: '3.8'
services:
  backend:
    build: ./backend
    env_file: .env.staging
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
    ports:
      - "3000:80"
    depends_on:
      - backend
